version: '3.8'
services:
    design-system:
        extends:
            file: docker-compose-common.yml
            service: design-system
        command: npm run dev
        volumes: 
            - design-system_npm_deps:/app/node_modules:ro
            - design-system_button_npm_deps:/app/components/ds-button/node_modules:ro
            - "./design-system:/app"
    header-panel:
        extends:
            file: docker-compose-common.yml
            service: header-panel
        command: npm run dev
        volumes: 
            - header-panel_npm_deps:/app/node_modules:ro
            - header-panel_ui_npm_deps:/app/ui/node_modules:ro
            - "./header-panel:/app"
    product-panel:
        extends:
            file: docker-compose-common.yml
            service: product-panel
        command: npm run dev
        volumes: 
            - product-panel_npm_deps:/app/node_modules:ro
            - product-panel_ui_npm_deps:/app/ui/node_modules:ro
            - "./product-panel:/app"
        links: 
            - "mongodb-server:mongodb-server"
        networks:
            - mongodb-network
            - nats
    shopping-cart:
        extends:
            file: docker-compose-common.yml
            service: shopping-cart
        command: npm run dev
        volumes: 
            - shopping-cart_npm_deps:/app/node_modules:ro
            - shopping-cart_ui_npm_deps:/app/ui/node_modules:ro
            - "./shopping-cart:/app"
        links: 
            - "mongodb-server:mongodb-server"
        networks:
            - mongodb-network
            - nats
    footer-panel:
        extends:
            file: docker-compose-common.yml
            service: footer-panel
        command: npm run dev        
        volumes: 
            - footer-panel_npm_deps:/app/node_modules:ro
            - footer-panel_ui_npm_deps:/app/ui/node_modules:ro
            - "./footer-panel:/app"
    mongodb-server:
        extends:
            file: docker-compose-common.yml
            service: mongodb-server
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb-server
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin123
        volumes:
            - mongodb-data
        depends_on:
            - mongodb-server
        networks:
            - mongodb-network
        ports:
            - 8090:8081
        healthcheck:
            test:  wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped
    container-app:
        build: 
            context: ./container-app
            dockerfile: Dockerfile
        command: npm run dev
        volumes: 
            - container-app_npm_deps:/app/node_modules:ro
            - "./container-app:/app"
        ports: 
            - 8080:3000
        depends_on:
            - design-system
            - header-panel
            - product-panel
            - shopping-cart
            - footer-panel
        links:
            - "design-system:design-system"
            - "header-panel:header-panel"
            - "product-panel:product-panel"
            - "shopping-cart:shopping-cart"
            - "footer-panel:footer-panel"
    nats:
        image: nats
        ports:
        - "8222:8222"
        networks: 
            - nats
volumes:
    mongodb-data:
        name: mongodb-data
    design-system_npm_deps:
        name: design-system_npm_deps
    design-system_button_npm_deps:
        name: design-system_button_npm_deps
    header-panel_npm_deps:
        name: header-panel_npm_deps
    header-panel_ui_npm_deps:
        name: header-panel_ui_npm_deps
    product-panel_npm_deps:
        name: product-panel_npm_deps
    product-panel_ui_npm_deps:
        name: product-panel_ui_npm_deps
    shopping-cart_npm_deps:
        name: shopping-cart_npm_deps
    shopping-cart_ui_npm_deps:
        name: shopping-cart_ui_npm_deps
    footer-panel_npm_deps:
        name: footer-panel_npm_deps
    footer-panel_ui_npm_deps:
        name: footer-panel_ui_npm_deps
    container-app_npm_deps:
        name: container-app_npm_deps
networks:
    mongodb-network:
        name: mongodb-network
    nats:
        name: nats