version: '3'
services:
    design-system:
        extends:
            file: docker-compose-common.yml
            service: design-system
        command: npm start
    header-panel:
        extends:
            file: docker-compose-common.yml
            service: header-panel
        command: npm start
    product-panel:
        extends:
            file: docker-compose-common.yml
            service: product-panel
        command: npm start
        links:
            - "mongodb-server:mongodb-server"
        networks:
            - mongodb-network
    shopping-cart:
        extends:
            file: docker-compose-common.yml
            service: shopping-cart
        command: npm start
        links: 
            - "mongodb-server:mongodb-server"
        networks:
            - mongodb-network
    footer-panel:
        extends:
            file: docker-compose-common.yml
            service: footer-panel
        command: npm start      
    mongodb-server:
        extends:
            file: docker-compose-common.yml
            service: mongodb-server
    container-app:
        build:
            context: ./container-app
            dockerfile: Dockerfile
        command: npm start
        ports:
            - 8080:3000
        depends_on:
            - design-system
            - header-panel
            - product-panel
            - shopping-cart
            - footer-panel
        links:
            - "design-system:design-system"
            - "header-panel:header-panel"
            - "product-panel:product-panel"
            - "shopping-cart:shopping-cart"
            - "footer-panel:footer-panel"
volumes:
    mongodb-data:
        name: mongodb-data
networks:
    mongodb-network:
        name: mongodb-network